forum/forum/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView,PasswordResetView,LogoutView
from posts.views import HomeView, PostSelfListView, PostDetailCommentView, PostCreateView
from profiles.views import ProfileFollowToggle, RegisterView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',HomeView.as_view(),name="home"),
   	url(r'^posts/',include("posts.urls",namespace="posts")),
   	url(r'^profiles/',include("profiles.urls",namespace="profiles")),
   	url(r'^follow/',ProfileFollowToggle.as_view(),name="follow"),
    url(r'^login/$',LoginView.as_view(),name='login'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^logout/$',LogoutView.as_view(),name='logout'),
    url(r'^password_reset/$',PasswordResetView.as_view(),name='password_reset'),    


 ]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/posts/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from posts.views import PostSelfListView,PostDetailCommentView,PostCreateView


urlpatterns = [
    url(r'^$',PostSelfListView.as_view(),name="my_posts"),
    url(r'^create/$',PostCreateView.as_view(),name="create"),
    url(r'^(?P<slug>[\w-]+)/$',PostDetailCommentView.as_view(),name="details"),
    
 ]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/templates/snippets/css.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">

forum/templates/snippets/form-snippet.html
	{% if form.errors %}
	{{form.errors}}
	{% endif %}
	<form method="POST" >{% csrf_token %}
	{{form.as_p}}
	<button type="submit">Save</button>
	</form>

forum/templates/snippets/header.html
{%  load static %}
<style type="text/css">
.nav a:hover{
background-color: #1E2524;

}

</style>

<div class="topnav" style="background-color: #000000" >
<br>
<div class="row">
<div class="col">

		<a  style=" text-decoration: none;padding: 20px;border: 1px solid cyan; color: cyan;" href="{% url 'home' %}"> Home </a>
		<a style="text-decoration: none;padding: 20px;border: 1px solid cyan;margin: 10px; color: cyan"  href="{% url 'posts:my_posts'  %}">My Posts</a>
<div style="text-align: center;">
<h1 style="color: White;margin-left: 300px;margin-top: -30px" >SocialForum.com</h1>

</div>
<!--<div class="nav">-->

		<!--<a  style=" text-decoration: none;padding: 10px; color: cyan" href="{% url 'home' %}"> Home </a>
		<a style="text-decoration: none;padding: 10px; color: cyan"  href="{% url 'posts:my_posts'  %}">My Posts</a>-->

	<!--</div>-->
	
</div>


<div class="col-sm-2">


	{% if request.user.is_authenticated %}
<!--<div class="row" style="height:30%">-->
	<!--<img  src='{% static "profiles/profile.png" %}' class="rounded-circle"  alt="my img" style="width: 20%;height: 100% ; padding: 10px;margin-right: 20px;margin-left: 50px">-->

<!--</div>-->

<div class="row" >

<i style="color: #FFFFFF; font-size: 20px; margin-left: -50px; margin-top:-10px" >Welcome, {{request.user.username}}</i>
<a  style="margin-left: 15px;margin-top: -10px; color: #FF0000; font-size:20px" href="{% url 'login' %}" >Log Out</a>

{%else%}
<div class="row" style="align-self: center;">
	<a  style="padding:20px; color: white ; float: right" href="{% url 'login' %}"> Login </a>
	<a  style="padding:20px; color: white ; float: right" href="{% url 'register' %}">Register</a>
</div>
{% endif %}

</div>



</div>

</div>



</div>

forum/templates/snippets/js.html
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>

forum/templates/snippets/nav.html
<div class="container">
	<a href="{% url 'home' %}"> Home </a>
	<a href="{% url 'posts:my_posts'  %}">My Posts</a>
	
</div>