forum/forum/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView,PasswordResetView,LogoutView
from posts.views import HomeView, PostSelfListView, PostDetailCommentView, PostCreateView
from profiles.views import ProfileFollowToggle, RegisterView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',HomeView.as_view(),name="home"),
   	url(r'^posts/',include("posts.urls",namespace="posts")),
   	url(r'^profiles/',include("profiles.urls",namespace="profiles")),
   	url(r'^follow/',ProfileFollowToggle.as_view(),name="follow"),
    url(r'^login/$',LoginView.as_view(),name='login'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^logout/$',LogoutView.as_view(),name='logout'),
    url(r'^password_reset/$',PasswordResetView.as_view(),name='password_reset'),    


 ]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/profiles/urls.py
from django.conf.urls import url
from .views import ProfileDetailView

urlpatterns = [
    url(r'^(?P<username>[\w-]+)/$',ProfileDetailView.as_view(),name="user_detail"),
]

forum/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>
		{% block title%}{% endblock title %}
		SocailForum.com
	</title>
	{% include "snippets/css.html"%}
</head>
<body>
	
	{% include "snippets/header.html" %}
	<div align="center"  style="align-self: center;" class="container">
	{% block content %} 

	{% endblock content %}

	</div>
	 
	{% include "snippets/css.html"%}
	</body>
</html>

forum/templates/home.html
<style type="text/css">
.card {
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
    transition: 0.3s;
    border-radius: 5px; /* 5px rounded corners */
    border-color: aqua;
}


</style>

{% extends "base.html" %}
{% block title %}
Home | {{block.super}}
{% endblock title %}

{% block content %}
{% if request.user.is_authenticated %}
<div class="container" >
	<ul style="list-style: none;">
	{% for obj in object_list %}
	<li style="padding: 20px">
	<div  class="card">
	<div class="card-header" >
	<h2><a style="text-decoration: none;" href="{{obj.get_absolute_url}}">{{obj.title}}</a></h2>
	<a href="{% url 'profiles:user_detail' username=obj.user.username %}"><i style="margin-right: 2px;float: right;">by @{{obj.user}}</i></a>	
	</div>

	<div class="card-body">
	<div class="col">
	<div class="row">
		{{obj.text|truncatechars:500}}
	</div>
	<div class="row">
		{% if obj.image %}
		<img class="img-thumbnail"  src="{{obj.image.url}}" alt="image" style="width: 50%;margin-left: auto;margin-right: auto;"  /><br>
		{% endif %}
	</div>
	</div>
	
	</div>
	</div>
	
	
		
		
	</li>
	{% endfor %}
</ul>

</div>
{% else %}
<h4>Welcome to SocialForum.com</h4>

{% endif %}

{% endblock content %}